### ISSUE TITLE
Line 97 in index.js throws error

### ISSUE THREAD

**Issue by yizhang25** [Wpdas/horizon-youtube-mp3#2]
Error message: C:\Users\dduo2\Documents\dev\FerretJava>node index
FERRET ACTIVE
[ 'https://www.youtube.com/watch?v=Xydf351l-gw' ]
C:\Users\dduo2\Documents\dev\FerretJava\node_modules\horizon-youtube-mp3\lib\index.js:97
    return callback(errorsType.NO_DESTINATION);
           ^

TypeError: callback is not a function
    at Function.HorizonMP3Core.download (C:\Users\dduo2\Documents\dev\FerretJava\node_modules\horizon-youtube-mp3\lib\index.js:97:12)
    at Object.HorizonMP3.download (C:\Users\dduo2\Documents\dev\FerretJava\node_modules\horizon-youtube-mp3\lib\index.js:295:18)
    at Play (C:\Users\dduo2\Documents\dev\FerretJava\index.js:41:25)
    at Client.<anonymous> (C:\Users\dduo2\Documents\dev\FerretJava\index.js:117:17)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (C:\Users\dduo2\Documents\dev\FerretJava\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\dduo2\Documents\dev\FerretJava\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\dduo2\Documents\dev\FerretJava\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\dduo2\Documents\dev\FerretJava\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)

**Comment by wpdas** [comment]
Hi @HyperOwl,

The problem was fixed. You can update the package and keep going with your project. 😄

**Comment by yizhang25** [comment]
Thanks!
